
/* --------------------------------------------------------------------
   Code generated by a SAS task k
   
   Generated on Friday, December 07, 2012 at 3:02:05 PM
   By task:     Import Data
   
   Source file: U:\Post_doc\Laurie_Manasvi\Phenotype_datanw.csv
   Server:      Local File System
   
   Output data: WORK.Phenotype_datanw2
   Server:      Local
   -------------------------------------------------------------------- */

DATA WORK.Phenotype_datanw2;
    LENGTH
        Animal_ID        $ 3
        Diet             $ 3
        DAPI_Stem_cells    8
        RED_Cell_proliferation   8
        YELLOW_Apoptosis   8 ;
    FORMAT
        Animal_ID        $CHAR3.
        Diet             $CHAR3.
        DAPI_Stem_cells  BEST2.
        RED_Cell_proliferation BEST1.
        YELLOW_Apoptosis BEST1. ;
    INFORMAT
        Animal_ID        $CHAR3.
        Diet             $CHAR3.
        DAPI_Stem_cells  BEST2.
        RED_Cell_proliferation BEST1.
        YELLOW_Apoptosis BEST1. ;
    INFILE 'C:\Users\ldstudent\AppData\Local\Temp\SEG6180\Phenotype_datanw-fbd127f4ecf5494dbe227e17927f0d25.txt'
        LRECL=14
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='7F'x
        MISSOVER
        DSD ;
    INPUT
        Animal_ID        : $CHAR3.
        Diet             : $CHAR3.
        DAPI_Stem_cells  : ?? BEST2.
        RED_Cell_proliferation : ?? BEST1.
        YELLOW_Apoptosis : ?? BEST1. ;
RUN;

proc print data=Phenotype_datanw;
run;
proc univariate data=Phenotype_datanw normal;
var DAPI_Stem_cells RED_Cell_proliferation YELLOW_Apoptosis;
run;

proc mixed data=Phenotype_datanw; 
class diet;
model DAPI_Stem_cells = diet;
lsmeans diet / diff=all adjust=tukey;
run;
proc genmod data = Phenotype_datanw;
  class diet;
  model DAPI_Stem_cells = diet / type3 dist=poisson;
  lsmeans diet /diff=all;
 /* repeated subject= Animal_ID; */
run;
proc genmod data = Phenotype_datanw;
  class diet;
  model DAPI_Stem_cells = diet / type3 dist=poisson scale=d;
  lsmeans diet /diff=all;
 /* repeated subject= Animal_ID; */
run;  

proc genmod data = Phenotype_datanw;
  class diet;
  model DAPI_Stem_cells = diet / type3 dist=poisson scale=d influence;
  lsmeans diet /diff=all;
 /* repeated subject= Animal_ID; */
run; 

/*                                 */
/*                                 */
proc mixed data=Phenotype_datanw; 
class diet;
model RED_Cell_proliferation = diet;
lsmeans diet / diff=all adjust=tukey;
run;
proc genmod data = Phenotype_datanw;
  class diet;
  model RED_Cell_proliferation = diet / type3 dist=poisson;
  lsmeans diet /diff=all;
run;
proc genmod data = Phenotype_datanw;
  class diet;
  model RED_Cell_proliferation = diet / type3 dist=poisson scale=d;
  lsmeans diet /diff=all;
run;

proc genmod data = Phenotype_datanw1;
  class diet;
  model YELLOW_Apoptosis = diet / type3 dist=poisson scale=d;
  lsmeans diet /diff=all;
  zeromodel /link=logit;
run;
